# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import api_pb2 as api__pb2


class MethodStub(object):
    """Remote procedure call method of API
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.gRPC = channel.unary_unary(
                '/Method/gRPC',
                request_serializer=api__pb2.Request.SerializeToString,
                response_deserializer=api__pb2.Response.FromString,
                )


class MethodServicer(object):
    """Remote procedure call method of API
    """

    def gRPC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MethodServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'gRPC': grpc.unary_unary_rpc_method_handler(
                    servicer.gRPC,
                    request_deserializer=api__pb2.Request.FromString,
                    response_serializer=api__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Method', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Method(object):
    """Remote procedure call method of API
    """

    @staticmethod
    def gRPC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Method/gRPC',
            api__pb2.Request.SerializeToString,
            api__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
